CREATE TABLE IF NOT EXISTS departments (
  id INT(5) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10,2) NOT NULL,
  departments_id INT(5) UNSIGNED ZEROFILL,
  FOREIGN KEY (departments_id) REFERENCES departments(id)
);

CREATE TABLE IF NOT EXISTS employees (
  id INT(10) UNSIGNED ZEROFILL AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  roles_id INT,
  manager_id INT UNSIGNED NULL DEFAULT NULL,
  FOREIGN KEY (roles_id) REFERENCES roles(id),
  FOREIGN KEY (manager_id) REFERENCES employees(id)
);
